wandb:
  entity: null
  resume: False
  run_name: "cpt_latent_llada_w-sim-4_middle-focused-sampling_symmetric-weighting_fullscale_260315_2020" # the name of this run in wandb, can be different from experiment.project


experiment:
    project: "LOG_continued_pretrain_latent_llada_fullscale" # need to be same of this file name
    num_node: 1 # the number of machines you have

model:
    pretrained_model: "/scratch/aszalay1/tianze/release_checkpoints/llada_warmup_coreset" # absolute path of your model

# sft dataset
dataset:
    arrow_dirs: 
        - "/scratch/aszalay1/tianze/cpt_data/sft_starcoder_18b_pyarrow"
        - "/scratch/aszalay1/tianze/cpt_data/fineweb_10b_pyarrow"

training:
    gradient_checkpointing_enable: False # if the sequence is very large, set as True
    gradient_accumulation_steps: 32
    batch_size_lm: 2 # the total batch size is num_node * num_gpu_per_node * gradient_accumulation_steps * batch_size_lm
    mixed_precision: "bf16"
    enable_tf32: True
    seed: 32
    num_train_epochs: 1
    max_grad_norm: 1
    warmup: False # whether in the warmup training phase of the latent gate
    flowmatch_loss_weighting_strategy: "symmetric" # "constant", "symmetric", "noise_focused", "clean_focused"
    num_sim_stages: 4
    sim_t_sampling: "middle_focused" # "uniform", "clean_noise_focused", "middle_focused"

optimizer:
    name: adamw
    params: # default adamw params
        learning_rate: 5e-5
        scale_lr: False # scale learning rate by total batch size
        beta1: 0.9
        beta2: 0.999
        weight_decay: 0.0
        epsilon: 1e-8

lr_scheduler:
    scheduler: "cosine"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 500
        min_lr_scale: 0.1
        power: 2.0
