wandb:
  entity: null
  resume: False
  run_name: "cpt_latent_llada_warmup_gate_large-global-bs_clean-focused_26-03-01_1225" # the name of this run in wandb, can be different from experiment.project


experiment:
    project: "continued_pretrain_latent_llada_warmup" # need to be same of this file name
    num_node: 1 # the number of machines you have

model:
    pretrained_model: "/scratch/aszalay1/tianze/models/latent_llada_8b" # absolute path of your model
    optimized_name: "llada_8b_instruct_latent_sft_openthoughts" # the output name for your optimized model, will be saved under sft_llada/ckpt

# sft dataset
dataset:
    optimization_data: "/openthoughts/openthoughts_sft_0" # "sft_openr1math_llada"

training:
    gradient_checkpointing_enable: False # if the sequence is very large, set as True
    gradient_accumulation_steps: 32
    batch_size_lm: 1 # the total batch size is num_node * num_gpu_per_node * gradient_accumulation_steps * batch_size_lm
    mixed_precision: "bf16"
    enable_tf32: True
    seed: 32
    num_train_epochs: 3
    max_grad_norm: 1
    method: "random_masking" # "random_masking""semi-ar"
    lower_p: 0.05
    upper_p: 0.95
    block_size: 16 # use for semi-ar
    mask_times_per_sample: 1 # for random_masking
    post_num: 32 # number of pad token need to be trained for each data point
    max_gen_length: 2048
    max_prompt_len: 1024
    warmup: True # whether in the warmup training phase of the latent gate
    flowmatch_loss_weighting_strategy: "clean_focused" # "constant", "symmetric", "noise_focused", "clean_focused"



optimizer:
    name: adamw
    params: # default adamw params
        learning_rate: 1e-5
        scale_lr: False # scale learning rate by total batch size
        beta1: 0.9
        beta2: 0.999
        weight_decay: 0.0
        epsilon: 1e-8

lr_scheduler:
    scheduler: "constant_with_warmup"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 100
        min_lr_scale: 0.1

